const rooms=[
{id:'ceo',name:'CEO Office',x:0,y:0,color:'#e8b4c4',furniture:[['🗄️',25,45],['🪑',130,105],['💻',115,45]]},
{id:'dev',name:'Development',x:220,y:0,color:'#9fc7ef',furniture:[['🖥️',35,45],['🖥️',125,45],['☕',155,130]]},
{id:'research',name:'Research Lab',x:440,y:0,color:'#a9d9c0',furniture:[['🔬',32,52],['📚',130,48],['🪴',155,135]]},
{id:'marketing',name:'Creative Studio',x:0,y:200,color:'#f1ce8e',furniture:[['🎨',30,48],['📸',130,48],['🛋️',105,130]]},
{id:'qa',name:'QA & Review',x:220,y:200,color:'#c5b4e8',furniture:[['🧪',30,48],['🖥️',125,48],['🧯',160,135]]},
{id:'lounge',name:'Team Lounge',x:440,y:200,color:'#b8d993',furniture:[['🛋️',30,58],['☕',125,55],['🎮',145,135]]}
];
const defaults=[
{id:'alpha',name:'Alpha',role:'CEO agent',model:'Qwen 3',room:'ceo',avatar:'🧠',shirt:'#e86c91',hair:'#59382f',energy:88,focus:82,mood:86,cpu:34,traits:['Analitičan','Ambiciozan','Vođa'],task:'Planira sljedeći proizvodni sprint',memory:['Pokrenuta nova faza enginea','Prioritet je osjećaj žive AI firme'],chat:[],x:105,y:110},
{id:'coder',name:'Nova',role:'Developer',model:'DeepSeek Coder',room:'dev',avatar:'👩‍💻',shirt:'#547de8',hair:'#3a2c28',energy:73,focus:91,mood:75,cpu:62,traits:['Brza','Logična','Noćna ptica'],task:'Gradi izometrijski engine',memory:['UI više nije običan dashboard'],chat:[],x:105,y:112},
{id:'researcher',name:'Atlas',role:'Researcher',model:'Llama 3.3',room:'research',avatar:'🔎',shirt:'#42a983',hair:'#6b472e',energy:81,focus:87,mood:79,cpu:45,traits:['Znatiželjan','Temeljit','Miran'],task:'Istražuje agent workflows',memory:['Sobe moraju mijenjati ponašanje agenta'],chat:[],x:98,y:115},
{id:'writer',name:'Mira',role:'Creative agent',model:'Gemma 3',room:'marketing',avatar:'✍️',shirt:'#e5a33d',hair:'#8a5438',energy:77,focus:74,mood:92,cpu:39,traits:['Kreativna','Društvena','Optimist'],task:'Oblikuje priču AI Sims OS-a',memory:['Vizual treba biti topao i razigran'],chat:[],x:102,y:110},
{id:'tester',name:'Pixel',role:'QA agent',model:'Mistral',room:'qa',avatar:'🧪',shirt:'#8a68d8',hair:'#352c43',energy:69,focus:89,mood:71,cpu:57,traits:['Skeptičan','Precizan','Uporan'],task:'Testira interakcije i stanje svijeta',memory:['Svaki klik mora imati smisla'],chat:[],x:105,y:112},
{id:'ops',name:'Bolt',role:'Ops agent',model:'Qwen 3',room:'lounge',avatar:'⚙️',shirt:'#67a64c',hair:'#4b4031',energy:64,focus:68,mood:84,cpu:51,traits:['Praktičan','Pouzdan','Automatizira'],task:'Čeka sljedeći deploy',memory:['GitHub Pages objavljuje main granu'],chat:[],x:100,y:112}
];
const stored=JSON.parse(localStorage.getItem('aiSimsV2')||'null');
let state=stored||{agents:defaults,selected:'alpha',day:1,minute:9*60,speed:1,tasks:['Dovrši izometrijsku kuću','Dodaj pravi lokalni AI','Napravi task board'],cost:0};
let zoom=1,pan={x:0,y:0},drag=null,tick=0;
const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
function save(){localStorage.setItem('aiSimsV2',JSON.stringify(state))}
function room(id){return rooms.find(r=>r.id===id)}
function agent(id){return state.agents.find(a=>a.id===id)}
function time(){let h=Math.floor(state.minute/60)%24,m=state.minute%60;return`Dan ${state.day} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function render(){renderHouse();renderList();renderInspector();$('worldTime').textContent=time();$('agentCount').textContent=state.agents.length;$('taskCount').textContent=state.tasks.length;$('costCount').textContent=`€${state.cost.toFixed(2)}`;$('speedLabel').textContent=state.speed===0?'PAUZA':state.speed===1?'1× BRZINA':'3× BRZINA';document.body.classList.toggle('night',state.minute<7*60||state.minute>19*60);$('dayIcon').textContent=document.body.classList.contains('night')?'🌙':'☀️';updateCamera()}
function renderHouse(){const h=$('house');h.innerHTML='';rooms.forEach(r=>{const el=document.createElement('div');el.className='room';el.style.cssText=`left:${r.x}px;top:${r.y}px;background:${r.color}`;el.innerHTML=`<div class="room-label">${r.name}</div>`;r.furniture.forEach(f=>{const n=document.createElement('div');n.className='furniture';n.textContent=f[0];n.style.left=f[1]+'px';n.style.top=f[2]+'px';el.appendChild(n)});state.agents.filter(a=>a.room===r.id).forEach(a=>{const n=document.createElement('div');n.className='agent'+(state.selected===a.id?' selected':'')+(a.walking?' walking':'')+(a.talking?' talking':'');n.style.left=a.x+'px';n.style.top=a.y+'px';n.style.setProperty('--shirt',a.shirt);n.style.setProperty('--hair',a.hair);n.innerHTML=`<div class="speech">${a.say||a.task}</div><div class="hair"></div><div class="head"></div><div class="body"></div><div class="legs"></div>`;n.onclick=e=>{e.stopPropagation();state.selected=a.id;save();render()};el.appendChild(n)});h.appendChild(el)})}
function renderList(){const l=$('agentList');l.innerHTML='';state.agents.forEach(a=>{const n=document.createElement('div');n.className='agent-list-item'+(state.selected===a.id?' selected':'');n.innerHTML=`<div class="mini-avatar">${a.avatar}</div><div><b>${a.name}</b><small>${a.role}</small></div><i class="status-dot"></i>`;n.onclick=()=>{state.selected=a.id;render()};l.appendChild(n)})}
function renderInspector(){const a=agent(state.selected);$('emptyInspector').classList.toggle('hidden',!!a);$('agentInspector').classList.toggle('hidden',!a);if(!a)return;$('avatarBig').textContent=a.avatar;$('agentName').textContent=a.name;$('agentRole').textContent=`${a.role} · ${room(a.room).name}`;$('agentModel').textContent=a.model;$('energy').value=a.energy;$('focus').value=a.focus;$('mood').value=a.mood;$('cpu').value=a.cpu;$('currentTask').textContent=a.task;$('traits').innerHTML=a.traits.map(t=>`<span>${t}</span>`).join('');$('memoryList').innerHTML=a.memory.slice(0,6).map(m=>`<li>${m}</li>`).join('');$('chatLog').innerHTML=a.chat.length?a.chat.slice(-8).map(m=>`<div class="message"><b>${m.from}:</b> ${m.text}</div>`).join(''):'<span>Nema poruka.</span>'}
function chooseActivity(a){const roll=Math.random();if(roll<.35){const target=room(a.room);a.x=35+Math.random()*125;a.y=70+Math.random()*75;a.walking=true;a.say='Idem do radnog mjesta…'}else if(roll<.55){const options=rooms.filter(r=>r.id!==a.room);const next=options[Math.floor(Math.random()*options.length)];a.room=next.id;a.x=45+Math.random()*115;a.y=82+Math.random()*60;a.walking=true;a.say=`Idem u ${next.name}.`;a.memory.unshift(`Posjetio ${next.name}`)}else{a.walking=false;a.talking=true;a.say=['Radim na zadatku.','Trebam kratki review.','Imam novu ideju!','Šaljem status timu.'][Math.floor(Math.random()*4)];a.chat.push({from:a.name,text:a.say})}setTimeout(()=>{a.walking=false;a.talking=false;renderHouse()},1200)}
function simulate(){if(!state.speed)return;tick++;state.minute+=5*state.speed;if(state.minute>=1440){state.minute=7*60;state.day++}state.cost+=.002*state.speed;state.agents.forEach(a=>{a.energy=clamp(a.energy-(Math.random()*1.4)*state.speed);a.focus=clamp(a.focus+(Math.random()*4-2));a.mood=clamp(a.mood+(Math.random()*3-1.5));a.cpu=clamp(25+Math.random()*55);if(tick%(state.speed===3?2:5)===0)chooseActivity(a)});save();render()}
function updateCamera(){$('camera').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}
$('viewport').onpointerdown=e=>{if(e.target.closest('.agent'))return;drag={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};$('viewport').classList.add('dragging')};window.onpointermove=e=>{if(!drag)return;pan.x=drag.px+e.clientX-drag.x;pan.y=drag.py+e.clientY-drag.y;updateCamera()};window.onpointerup=()=>{drag=null;$('viewport').classList.remove('dragging')};$('viewport').onwheel=e=>{e.preventDefault();zoom=clamp(zoom-e.deltaY*.001,.55,1.6);updateCamera()};$('zoomIn').onclick=()=>{zoom=clamp(zoom+.12,.55,1.6);updateCamera()};$('zoomOut').onclick=()=>{zoom=clamp(zoom-.12,.55,1.6);updateCamera()};$('zoomReset').onclick=()=>{zoom=1;pan={x:0,y:0};updateCamera()};
function setSpeed(s){state.speed=s;document.querySelectorAll('.play-controls button').forEach(b=>b.classList.remove('active'));({0:'pauseBtn',1:'playBtn',3:'fastBtn'})[s]&&$(({0:'pauseBtn',1:'playBtn',3:'fastBtn'})[s]).classList.add('active');save();render()}
$('pauseBtn').onclick=()=>setSpeed(0);$('playBtn').onclick=()=>setSpeed(1);$('fastBtn').onclick=()=>setSpeed(3);$('addTaskBtn').onclick=()=>{const t=prompt('Novi zadatak za AI kompaniju:');if(!t)return;state.tasks.unshift(t);const a=agent(state.selected)||state.agents[0];a.task=t;a.memory.unshift(`Novi zadatak: ${t}`);save();render()};$('sendChat').onclick=()=>{const input=$('chatText'),text=input.value.trim(),a=agent(state.selected);if(!text||!a)return;a.chat.push({from:'Ti',text});a.task=text;a.say='Primljeno. Krećem!';a.talking=true;a.memory.unshift(`Uputa: ${text}`);input.value='';save();render();setTimeout(()=>{a.talking=false;renderHouse()},1600)};$('chatText').onkeydown=e=>{if(e.key==='Enter')$('sendChat').click()};$('resetBtn').onclick=()=>{if(confirm('Napraviti novi AI Sims svijet?')){localStorage.removeItem('aiSimsV2');location.reload()}};
setInterval(simulate,1100);render();